name: mobile_app
description: App móvil para repartidores - Sistema de Envíos
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  
  # HTTP
  http: ^1.1.2
  
  # State Management
  provider: ^6.1.1
  
  # UI
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  
  # Utils
  intl: ^0.18.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true